# Docker build with GPU-accelerated index building via Cloud Run Jobs
# Triggers: push to main, tag v*, PR to main
#
# PR builds → GAR mcp-builds registry (dev testing, no DockerHub)
# Main/tag builds → DockerHub (production)

substitutions:
  _DOCKERHUB_REPO: plainsightai/openfilter-mcp
  _GAR_REPO: us-west1-docker.pkg.dev/plainsightai-dev/mcp-builds/openfilter-mcp
  _GCS_BUCKET: ${PROJECT_ID}-build-artifacts
  _REGION: us-central1
  _PR_NUMBER: ''  # Set by PR trigger via --substitutions

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-username/versions/latest
      env: 'DOCKERHUB_USERNAME'
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-token/versions/latest
      env: 'DOCKERHUB_TOKEN'
    - versionName: projects/${PROJECT_ID}/secrets/openfilter-mcp-hf-token/versions/latest
      env: 'HF_TOKEN'

steps:
  # Upload source, run GPU job, download index
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['HF_TOKEN']
    args:
      - '-c'
      - |
        set -e
        tar czf /tmp/src.tar.gz --exclude='.git' --exclude='indexes' .
        gsutil cp /tmp/src.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz

        gcloud run jobs update index-builder --region=${_REGION} \
          --image=nvidia/cuda:12.4.0-devel-ubuntu22.04 \
          --command=bash \
          --set-env-vars=HF_TOKEN="$$HF_TOKEN" \
          --args="-c,set -ex; apt-get update && apt-get install -y git gcc g++ cmake curl python3 python3-pip; curl -LsSf https://astral.sh/uv/install.sh | sh; curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts; export PATH=/root/.local/bin:/root/google-cloud-sdk/bin:\$$PATH; cd /tmp; gcloud storage cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz .; tar xzf src.tar.gz; uv sync; uv run index; tar czf idx.tar.gz indexes/ openfilter_repos_clones/; gcloud storage cp idx.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz"

        gcloud run jobs execute index-builder --region=${_REGION} --wait
        gsutil cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz /workspace/
        tar xzf /workspace/idx.tar.gz -C /workspace/

  # Docker build and push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
    args:
      - '-c'
      - |
        # Set up QEMU for multiplatform builds
        docker run --privileged multiarch/qemu-user-static --reset -p yes

        # Create Dockerfile
        cat > Dockerfile.gpu << 'EOF'
        FROM python:3.12-slim
        COPY --from=ghcr.io/astral-sh/uv:0.9.6 /uv /uvx /bin/
        RUN apt-get update && apt-get install -y git curl gcc g++ && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY pyproject.toml README.md ./
        COPY src/ src/
        COPY code-context/ code-context/
        COPY indexes/ indexes/
        COPY openfilter_repos_clones/ openfilter_repos_clones/
        ENV CMAKE_ARGS="-DGGML_CUDA=off"
        RUN uv sync --locked || uv sync
        CMD ["uv", "run", "python", "-m", "openfilter_mcp.server"]
        EOF

        # Create buildx builder with docker-container driver for multiplatform support
        docker buildx create --name multiarch-builder --driver docker-container --use
        docker buildx inspect --bootstrap

        # PR builds → GAR only (no DockerHub, no latest tag)
        if [[ -n "${_PR_NUMBER}" ]]; then
          echo "PR build #${_PR_NUMBER}: pushing to GAR mcp-builds"
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${_GAR_REPO}:pr-${_PR_NUMBER} \
            -t ${_GAR_REPO}:${SHORT_SHA} \
            --push \
            -f Dockerfile.gpu .
          exit 0
        fi

        # Main/tag builds → DockerHub
        echo "$$DOCKERHUB_TOKEN" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin

        # Only add 'latest' tag for version tags (v*)
        if [[ "${TAG_NAME}" =~ ^v ]]; then
          echo "Version tag build: ${TAG_NAME}"
          _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA} -t ${_DOCKERHUB_REPO}:latest -t ${_DOCKERHUB_REPO}:${TAG_NAME#v}"
        else
          echo "Main branch build: SHA ${SHORT_SHA}"
          _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA}"
        fi
        echo "Building with tags: $$_TAGS"

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          $$_TAGS \
          --push \
          -f Dockerfile.gpu .

  # Cleanup
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['bash', '-c', 'gsutil -m rm -r gs://${_GCS_BUCKET}/builds/${BUILD_ID}/ || true']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: '4200s'
