# Run unit tests
# Triggers: push to main, PRs to main

steps:
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        apt-get update && apt-get install -y git gcc g++ cmake curl
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH" CMAKE_ARGS="-DGGML_CUDA=off"
        uv sync --dev
        uv run pytest tests/ -v --tb=short

options:
  machineType: 'E2_HIGHCPU_8'
