# Docker build with GPU-accelerated index building via Cloud Run Jobs
# Triggers (configured in infrastructure/terraform/gcp/artifacts/cloudbuild-triggers.tf):
#   PR builds       → GAR oci registry (ephemeral, for review)
#   Dev tag (v*-dev) → GAR oci registry (dev testing, no DockerHub)
#   Release tag (v*) → DockerHub (production, latest if semver >= current)
#
# Dry-run by default — set _DRY_RUN=false in the Terraform trigger to actually push.

substitutions:
  _DRY_RUN: 'true'  # Terraform trigger overrides to "false" for automated runs
  _SLIM_ONLY: 'false'  # Set to "true" to skip GPU indexing and full build
  _DOCKERHUB_REPO: plainsightai/openfilter-mcp
  _GAR_REPO: us-west1-docker.pkg.dev/plainsightai-dev/oci/openfilter-mcp
  _GCS_BUCKET: ${PROJECT_ID}-build-artifacts
  _REGION: us-central1
  _PR_NUMBER: ''  # Set by PR trigger via --substitutions

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-username/versions/latest
      env: 'DOCKERHUB_USERNAME'
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-token/versions/latest
      env: 'DOCKERHUB_TOKEN'
    - versionName: projects/${PROJECT_ID}/secrets/openfilter-mcp-hf-token/versions/latest
      env: 'HF_TOKEN'

steps:
  # Step 1: Upload source, run GPU job, download index
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['HF_TOKEN']
    args:
      - '-c'
      - |
        set -e
        # Auto-detect slim-only from tag name (e.g. v1.0.0-slim-dev)
        SLIM_ONLY="${_SLIM_ONLY}"
        if [[ "${TAG_NAME}" == *slim* ]]; then SLIM_ONLY=true; fi
        if [[ "$$SLIM_ONLY" == "true" ]]; then echo "SLIM_ONLY: skipping index build"; exit 0; fi
        tar czf /tmp/src.tar.gz --exclude='.git' --exclude='indexes' .
        gsutil cp /tmp/src.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz

        gcloud run jobs update index-builder --region=${_REGION} \
          --image=nvidia/cuda:12.4.0-devel-ubuntu22.04 \
          --command=bash \
          --set-env-vars=HF_TOKEN="$$HF_TOKEN" \
          --args="-c,set -ex; apt-get update && apt-get install -y git gcc g++ cmake curl python3 python3-pip; curl -LsSf https://astral.sh/uv/install.sh | sh; curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts; export PATH=/root/.local/bin:/root/google-cloud-sdk/bin:\$$PATH; cd /tmp; gcloud storage cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz .; tar xzf src.tar.gz; uv python install 3.11; uv sync --python 3.11 --group code-search; uv run index; tar czf idx.tar.gz indexes/ openfilter_repos_clones/; gcloud storage cp idx.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz"

        gcloud run jobs execute index-builder --region=${_REGION} --wait
        gsutil cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz /workspace/
        tar xzf /workspace/idx.tar.gz -C /workspace/

        # Configure GAR auth for PR and dev builds
        if [[ -n "${_PR_NUMBER}" ]] || [[ "${TAG_NAME}" =~ ^v.*-dev(-slim)?$$ ]] || [[ "${TAG_NAME}" =~ ^v.*-slim-dev$$ ]]; then
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
          ACCESS_TOKEN=$$(gcloud auth print-access-token)
          echo "$$ACCESS_TOKEN" > /workspace/.gar_token
        fi

  # Step 2: Full Docker build (GPU image with code-context + indexes)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
    env: &docker-env
      - 'DRY_RUN=${_DRY_RUN}'
      - 'TAG_NAME=${TAG_NAME}'
      - 'SHORT_SHA=${SHORT_SHA}'
      - '_PR_NUMBER=${_PR_NUMBER}'
      - '_GAR_REPO=${_GAR_REPO}'
      - '_DOCKERHUB_REPO=${_DOCKERHUB_REPO}'
    args:
      - '-c'
      - |
        SLIM_ONLY="${_SLIM_ONLY}"; if [[ "${TAG_NAME}" == *slim* ]]; then SLIM_ONLY=true; fi
        if [[ "$$SLIM_ONLY" == "true" ]]; then echo "SLIM_ONLY: skipping full build"; exit 0; fi
        bash scripts/docker-build.sh --dockerfile Dockerfile.gpu --tag-suffix "" --latest-tag "latest"

  # Step 3: Slim Docker build (no code-context, no indexes, no ML deps)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
    env: *docker-env
    args:
      - '-c'
      - bash scripts/docker-build.sh --dockerfile Dockerfile.slim --tag-suffix "-slim" --latest-tag "latest-slim"

  # Step 4: Cleanup build artifacts from GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['bash', '-c', 'gsutil -m rm -r gs://${_GCS_BUCKET}/builds/${BUILD_ID}/ || true']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: '7200s'  # 2 hours - multiplatform builds take ~90min
