# Docker build with GPU-accelerated index building via Cloud Run Jobs
# Triggers: push to main, tag v*, PR to main
#
# PR builds → GAR oci registry (dev testing, no DockerHub)
# Dev tag builds (v*-dev) → GAR oci registry (dev testing, no DockerHub)
# Main/tag builds → DockerHub (production)

substitutions:
  _DOCKERHUB_REPO: plainsightai/openfilter-mcp
  _GAR_REPO: us-west1-docker.pkg.dev/plainsightai-dev/oci/openfilter-mcp
  _GCS_BUCKET: ${PROJECT_ID}-build-artifacts
  _REGION: us-central1
  _PR_NUMBER: ''  # Set by PR trigger via --substitutions

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-username/versions/latest
      env: 'DOCKERHUB_USERNAME'
    - versionName: projects/${PROJECT_ID}/secrets/dockerhub-token/versions/latest
      env: 'DOCKERHUB_TOKEN'
    - versionName: projects/${PROJECT_ID}/secrets/openfilter-mcp-hf-token/versions/latest
      env: 'HF_TOKEN'

steps:
  # Upload source, run GPU job, download index
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv: ['HF_TOKEN']
    args:
      - '-c'
      - |
        set -e
        tar czf /tmp/src.tar.gz --exclude='.git' --exclude='indexes' .
        gsutil cp /tmp/src.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz

        gcloud run jobs update index-builder --region=${_REGION} \
          --image=nvidia/cuda:12.4.0-devel-ubuntu22.04 \
          --command=bash \
          --set-env-vars=HF_TOKEN="$$HF_TOKEN" \
          --args="-c,set -ex; apt-get update && apt-get install -y git gcc g++ cmake curl python3 python3-pip; curl -LsSf https://astral.sh/uv/install.sh | sh; curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts; export PATH=/root/.local/bin:/root/google-cloud-sdk/bin:\$$PATH; cd /tmp; gcloud storage cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/src.tar.gz .; tar xzf src.tar.gz; uv sync --extra code-search; uv run index; tar czf idx.tar.gz indexes/ openfilter_repos_clones/; gcloud storage cp idx.tar.gz gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz"

        gcloud run jobs execute index-builder --region=${_REGION} --wait
        gsutil cp gs://${_GCS_BUCKET}/builds/${BUILD_ID}/idx.tar.gz /workspace/
        tar xzf /workspace/idx.tar.gz -C /workspace/

        # Configure GAR auth for PR and dev builds
        if [[ -n "${_PR_NUMBER}" ]] || [[ "${TAG_NAME}" =~ ^v.*-dev$$ ]]; then
          # Get access token and save it for the docker step
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet
          ACCESS_TOKEN=$$(gcloud auth print-access-token)
          echo "$$ACCESS_TOKEN" > /workspace/.gar_token
        fi

  # Docker build and push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
    args:
      - '-c'
      - |
        # Set up QEMU for multiplatform builds
        docker run --privileged multiarch/qemu-user-static --reset -p yes

        # Configure GAR auth if this is a PR or dev build
        if [[ -n "${_PR_NUMBER}" ]] || [[ "${TAG_NAME}" =~ ^v.*-dev$$ ]]; then
          # Create docker config with credentials stored directly (not via credential helper)
          # This is needed because the buildx container doesn't have docker-credential-gcloud
          if [[ -f /workspace/.gar_token ]]; then
            GAR_TOKEN=$$(cat /workspace/.gar_token)
            # Use the auth format that docker expects (base64 encoded username:password)
            AUTH_B64=$$(echo -n "oauth2accesstoken:$$GAR_TOKEN" | base64 -w0)
            mkdir -p /builder/home/.docker
            # Create config.json with the auth entry using printf to avoid YAML issues
            printf '{\n  "auths": {\n    "us-west1-docker.pkg.dev": {\n      "auth": "%s"\n    }\n  }\n}\n' "$$AUTH_B64" > /builder/home/.docker/config.json
            echo "GAR auth configured for us-west1-docker.pkg.dev"
            cat /builder/home/.docker/config.json
          fi
        fi

        # Create Dockerfile
        cat > Dockerfile.gpu << 'EOF'
        FROM python:3.12-slim
        COPY --from=ghcr.io/astral-sh/uv:0.9.6 /uv /uvx /bin/
        RUN apt-get update && apt-get install -y git curl gcc g++ && rm -rf /var/lib/apt/lists/*
        WORKDIR /app
        COPY pyproject.toml README.md ./
        COPY src/ src/
        COPY code-context/ code-context/
        COPY indexes/ indexes/
        COPY openfilter_repos_clones/ openfilter_repos_clones/
        ENV CMAKE_ARGS="-DGGML_CUDA=off"
        RUN uv sync --locked --extra code-search || uv sync --extra code-search
        CMD ["uv", "run", "python", "-m", "openfilter_mcp.server"]
        EOF

        # Create buildx builder with docker-container driver for multiplatform support
        # Pass the docker config to buildkit via environment variable
        docker buildx rm multiarch-builder 2>/dev/null || true
        DOCKER_CONFIG=/builder/home/.docker docker buildx create --name multiarch-builder \
          --driver docker-container \
          --use
        docker buildx inspect --bootstrap

        # PR builds → GAR only (no DockerHub, no latest tag)
        if [[ -n "${_PR_NUMBER}" ]]; then
          echo "PR build #${_PR_NUMBER}: pushing to GAR oci"
          # Set DOCKER_CONFIG for buildx to find credentials
          DOCKER_CONFIG=/builder/home/.docker docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${_GAR_REPO}:pr-${_PR_NUMBER} \
            -t ${_GAR_REPO}:${SHORT_SHA} \
            --push \
            -f Dockerfile.gpu .
          exit 0
        fi

        # Dev tag builds (v*-dev) → GAR only
        if [[ "${TAG_NAME}" =~ ^v.*-dev$$ ]]; then
          echo "Dev tag build: ${TAG_NAME} → pushing to GAR oci"
          # Extract version without v prefix using sed
          DEV_VERSION=$$(echo "${TAG_NAME}" | sed 's/^v//')
          echo "TAG_NAME=${TAG_NAME}, DEV_VERSION=$$DEV_VERSION"
          # Set DOCKER_CONFIG for buildx to find credentials
          DOCKER_CONFIG=/builder/home/.docker docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${_GAR_REPO}:$$DEV_VERSION \
            -t ${_GAR_REPO}:${SHORT_SHA} \
            --push \
            -f Dockerfile.gpu .
          exit 0
        fi

        # Main/tag builds → DockerHub
        echo "$$DOCKERHUB_TOKEN" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin

        # Only add 'latest' tag for version tags (v*) if newer than current latest
        if [[ "${TAG_NAME}" =~ ^v ]]; then
          echo "Version tag build: ${TAG_NAME}"
          NEW_VERSION=$$(echo "${TAG_NAME}" | sed 's/^v//')

          # Fetch current latest version from DockerHub by finding which semver tag shares latest's digest
          LATEST_DIGEST=$$(curl -s "https://hub.docker.com/v2/repositories/${_DOCKERHUB_REPO}/tags/latest" | \
            jq -r '.images[0].digest // empty')

          if [[ -n "$$LATEST_DIGEST" ]]; then
            # Find the v* tag that matches this digest
            CURRENT_VERSION=$$(curl -s "https://hub.docker.com/v2/repositories/${_DOCKERHUB_REPO}/tags?page_size=100" | \
              jq -r --arg digest "$$LATEST_DIGEST" \
              '.results[] | select(.images[].digest == $$digest) | .name | select(test("^v?[0-9]+\\.[0-9]+\\.[0-9]+$"))' | \
              sed 's/^v//' | head -1)
          fi
          CURRENT_VERSION="$${CURRENT_VERSION:-0.0.0}"
          echo "Current latest version: $$CURRENT_VERSION, New version: $$NEW_VERSION"

          # Compare versions (semver): returns 0 if $$1 >= $$2
          version_gte() {
            [ "$$(printf '%s\n' "$$1" "$$2" | sort -V | tail -n1)" = "$$1" ]
          }

          if version_gte "$$NEW_VERSION" "$$CURRENT_VERSION"; then
            echo "New version $$NEW_VERSION >= current $$CURRENT_VERSION, tagging as latest"
            _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA} -t ${_DOCKERHUB_REPO}:latest -t ${_DOCKERHUB_REPO}:$$NEW_VERSION"
          else
            echo "New version $$NEW_VERSION < current $$CURRENT_VERSION, skipping latest tag"
            _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA} -t ${_DOCKERHUB_REPO}:$$NEW_VERSION"
          fi
        else
          echo "Main branch build: SHA ${SHORT_SHA}"
          _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA}"
        fi
        echo "Building with tags: $$_TAGS"

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          $$_TAGS \
          --push \
          -f Dockerfile.gpu .

  # Docker build and push (slim variant - no code search, no indexes)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
    args:
      - '-c'
      - |
        # Re-setup buildx and QEMU (each Cloud Build step is a fresh container)

        # Configure GAR auth if this is a PR or dev build
        if [[ -n "${_PR_NUMBER}" ]] || [[ "${TAG_NAME}" =~ ^v.*-dev$$ ]]; then
          if [[ -f /workspace/.gar_token ]]; then
            GAR_TOKEN=$$(cat /workspace/.gar_token)
            AUTH_B64=$$(echo -n "oauth2accesstoken:$$GAR_TOKEN" | base64 -w0)
            mkdir -p /builder/home/.docker
            printf '{\n  "auths": {\n    "us-west1-docker.pkg.dev": {\n      "auth": "%s"\n    }\n  }\n}\n' "$$AUTH_B64" > /builder/home/.docker/config.json
          fi
        fi

        # Recreate buildx builder (each step gets a fresh container)
        docker run --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx rm multiarch-builder 2>/dev/null || true
        DOCKER_CONFIG=/builder/home/.docker docker buildx create --name multiarch-builder \
          --driver docker-container \
          --use
        docker buildx inspect --bootstrap

        # PR builds → GAR only
        if [[ -n "${_PR_NUMBER}" ]]; then
          echo "PR slim build #${_PR_NUMBER}: pushing to GAR oci"
          DOCKER_CONFIG=/builder/home/.docker docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${_GAR_REPO}:pr-${_PR_NUMBER}-slim \
            -t ${_GAR_REPO}:${SHORT_SHA}-slim \
            --push \
            -f Dockerfile.slim .
          exit 0
        fi

        # Dev tag builds (v*-dev) → GAR only
        if [[ "${TAG_NAME}" =~ ^v.*-dev$$ ]]; then
          DEV_VERSION=$$(echo "${TAG_NAME}" | sed 's/^v//')
          echo "Dev tag slim build: ${TAG_NAME} → pushing to GAR oci"
          DOCKER_CONFIG=/builder/home/.docker docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${_GAR_REPO}:$$DEV_VERSION-slim \
            -t ${_GAR_REPO}:${SHORT_SHA}-slim \
            --push \
            -f Dockerfile.slim .
          exit 0
        fi

        # Main/tag builds → DockerHub
        echo "$$DOCKERHUB_TOKEN" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin

        if [[ "${TAG_NAME}" =~ ^v ]]; then
          NEW_VERSION=$$(echo "${TAG_NAME}" | sed 's/^v//')

          LATEST_DIGEST=$$(curl -s "https://hub.docker.com/v2/repositories/${_DOCKERHUB_REPO}/tags/latest-slim" | \
            jq -r '.images[0].digest // empty')

          if [[ -n "$$LATEST_DIGEST" ]]; then
            CURRENT_VERSION=$$(curl -s "https://hub.docker.com/v2/repositories/${_DOCKERHUB_REPO}/tags?page_size=100" | \
              jq -r --arg digest "$$LATEST_DIGEST" \
              '.results[] | select(.images[].digest == $$digest) | .name | select(test("^v?[0-9]+\\.[0-9]+\\.[0-9]+-slim$")) | sub("-slim$"; "")' | \
              sed 's/^v//' | head -1)
          fi
          CURRENT_VERSION="$${CURRENT_VERSION:-0.0.0}"

          version_gte() {
            [ "$$(printf '%s\n' "$$1" "$$2" | sort -V | tail -n1)" = "$$1" ]
          }

          if version_gte "$$NEW_VERSION" "$$CURRENT_VERSION"; then
            _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA}-slim -t ${_DOCKERHUB_REPO}:latest-slim -t ${_DOCKERHUB_REPO}:$$NEW_VERSION-slim"
          else
            _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA}-slim -t ${_DOCKERHUB_REPO}:$$NEW_VERSION-slim"
          fi
        else
          _TAGS="-t ${_DOCKERHUB_REPO}:${SHORT_SHA}-slim"
        fi
        echo "Building slim with tags: $$_TAGS"

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          $$_TAGS \
          --push \
          -f Dockerfile.slim .

  # Cleanup
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['bash', '-c', 'gsutil -m rm -r gs://${_GCS_BUCKET}/builds/${BUILD_ID}/ || true']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: '7200s'  # 2 hours - multiplatform builds take ~90min
